### PR TITLE
fix rake tests to run under windows

### PR DESCRIPTION
**Pull request by uujava**
Please, consider merging fix for running test rake tests under windows . 
This change should be safe for linux.

This fixes:
``` 
\r\n line ending in windows
```
```
:=>; File.pathSeparator under windows
```
```
 Issue with File.unlink when files locked by antivirus
```

### CODE REVIEW

**Comment by baroquebobcat** [comment]
Hi,
Thanks for the patch.

Could you file an issue against JRuby too for the file lock thing? Do you get that with CRuby as well?

Instead of using `File.pathSeparator`, could you use the `Mirah::Env.encode_paths` method? You'd need to break up the class paths into arrays, but I think it would make things clearer.

**Comment by baroquebobcat** [comment]
I'd like to merge the windows build fixes, and to look at the other feature additions, but could you break them out into separate pull requests?

**Comment by uujava** [comment]
Sorry, missed the fact that I'm developing on a single master branch. Will try to split it somehow.

**Comment by uujava** [comment]
closed to split into separate pull requests

**Pull request closed without merging**
