### PR TITLE
Do not link twice.

### PR DESCRIPTION
**Pull request by felixvf**

### CODE REVIEW

**Comment by uujava** [comment]
Just wonder if it's performance fix or there could be other issues with double linking?

**Comment by felixvf** [comment]
It is one small step into the direction of fixing #420, #421, #423 by implementing reluctant inference: In a first stage, _all_ code is scanned and appropriate TypeFutures are generated and no type inferences are drawn. Only after that phase is over, the actual type inference happens. Because all information is available at that stage, no inference choice needs to be made and thus no conclusion can become wrong after it was drawn (which is currently the case with the current compiler). Type inference becomes monotonous. This means that each TypeFuture is only resolved exactly one time, not multiple times (as it is now). A corollary (and requirement for monotonicity) is that for each BytecodeMirror, its supertypes are set exactly 1 time, and its class intrinsic are added exactly one time.

During that work, I found that this requirement was not met, because linking can happen multiple times. Hence this should be fixed.

**Comment by uujava** [comment]
Thank you for elaborate comment on this. 
Is it possible to explain a bit more new approach to solve the TypeFuture cyclic dependency graph.
Current approach, as far as I can understand it, is:
- "fire" resolved type to all listeners for the current future
-  listeners "widen" if possible and refire "widen" type if changed

It should eventually resolve if possible (might, currently, depends on resolution order).
And now we have multiple linking for mirror type system anyway.

**Comment by felixvf** [comment]
One attempt to solve this is to explicitly not support widening in cyclic cases:

All TypeFutures are resolved reluctantly, but then as far as possible monotonously. If any TypeFutures remain unresolved, then the remaining ones are the ones with cyclic dependencies (or ones depending on ones with cycling dependencies). The only TypeFutures with cyclic dependencies are AFAIK AssignableTypeFutures. Their output is unresolved and some of their inputs are unresolved. (And at least one input depends on the output.) For this special case, the unresolved input's type is imputed to be the same as the resolved input's type, hence resolution can proceed.

However, unlike the current implementation, if that makes type inference fail, there will be _no_ backtracking, just a compilation error. The error message will request the user to explicitly provide the type.

So

```mirah
def fib(i:int)
	if i < 2 then
		1
	else
		fib(i - 1) + fib(i - 2)
	end
end
```
will successfully compile, as will
```mirah
def fib(i:int)
	if i >= 2 then
		fib(i - 1) + fib(i - 2)
	else
		1
	end
end
```
(the the first input of the AssignableTypeFuture is allowed to be unresolved)

This will be better than Scala as of http://docs.scala-lang.org/tutorials/tour/local-type-inference.html

However, code like this:

```mirah
def foo(i:int)
	if i < 2 then
		bar(i)
	else
		["result"]
	end
end

def bar(i:int)
	if i < 1 then
		"result"
	else
		foo(i-1)
	end
end
```

may not compile successfully (which it does now) without a type annotation. The reason is that the return type of method `bar` will be attempted to be resolved as `java.lang.String`, but then later it will turn out that method `foo` has return type `java.lang.Object` and thus method `bar` also has return type `java.lang.Object` and not `java.lang.String`, as initially assumed.

I'm not sure about the negative impact of basically removing a feature of the Mirah compiler (replacing elaborate guessing of a type when faced with cyclic type dependencies by simple guessing of a type when faced with cyclic type dependencies), but because the guesses are not always correct (or produce not always what the programmer intended) (see #423), I think it is better 

1. to make transparent to the programmer that the compiler is guessing and
2. when faced with the decision whether to compile successfully, but with an unexpected behavior, or to compile with an error, then to compile with an error.

Additionally, I assume that removing backtracking will make the compiler faster.

**Comment by uujava** [comment]
That has pretty much sense and looks as feasible limitation for me. Thank you.

**Comment by uujava** [comment]
One case come to mind that is relatively frequent in the code:
```
x = if some_check
  Double.new 1
else
  Long.new 1
end
```
Wouldn't it require an additional casting initializer with new approach:
```
x = Number nil
x = if some_check
  Double.new 1
else
  Long.new 1
end
```

Note, we have tens of that kind of code even in compiler. Example:
```
    arguments = if mdef
      MethodDefinition(mdef).arguments
    elsif block_parent
      Block(block_parent).arguments
    end
```

**Comment by felixvf** [comment]
No, there would be no casting initializer necessary, because the compiler can successfully infer that `x` is of type `Number`, because both branches of the `if` statement get their type resolved _independently_ of (and before) the type of `x` (there is no recursion involved). The problem discussed above only happens when there is a cyclic type dependency (a TypeFuture being dependent on another TypeFuture and finally being dependent on itself), which is not very common.

**Comment by uujava** [comment]
I see. Thank you.

**Pull request merged**
