### PR TITLE
Allow to create the mirah equivalent of "static final long serialVersionUID = 123L" 

### PR DESCRIPTION
**Pull request by felixvf**
Note that this depends on https://github.com/mirah/mirah-parser/pull/20

### CODE REVIEW

**Comment by uujava** [comment]
Note, support for ACC_* modifiers implemented differently in uujava\mirah fork. I'm not sure parser modification was correct approach, but my opinion - modifier keywords should be a part of language not macros.

**Comment by felixvf** [comment]
## Method modifiers

I'm not married to which how class or method modifiers are implemented. Having seen https://github.com/mirah/mirah/blob/d7c85069d7e6d6db51c88030396d0fdacc8839b7/src/org/mirah/builtins/object_extensions.mirah#L80 , I thought the principle of using macros for both "abstract" and "private" could be extended to support also "synchronized" as well as "native" (see mirah/mirah#308). If there is a different implementation with the same syntax and result, I do not see a problem per se. The different proposals here are "Ruby style" (implement most of the language in itself) vs. "Java style" (implement most of the language in the parser). For Mirah, which is Ruby syntax with Java semantics, this is a fine question. ;-) I'm okay with either answer.

## Field modifiers

However, field modifiers are a different thing. In Mirah, fields (=class variables and instance variables) are defined implicitly (by mere assignment) unlike methods and classes, which are defined explicitly. There is no canonical place where a field is defined. There can be multiple field assignments in one class definition.

Currently, we have two proposals here:

mirah/mirah#302:
```mirah
class Foo
  static_final :serialVersionUID, -1234567890123456789
  transient :bar
  
  def operate1
  	@bar = 1
  end
  
  def operate2
  	@bar = 2
  end
end
```

mirah/mirah-parser#21 as far as I understand:
```mirah
class Foo
  
  def operate1
  	transient @bar = 1
  end
  
  def operate2
  	transient @bar = 2
  end
  
  self.initialize
  	static final @@serialVersionUID = -1234567890123456789 
  end
end
```

Probably I do not understand the second proposal very well. So I have some questions:

1. What happens if there are multiple FieldAssigns (e.g. in operate1() as well as in operate2())?
  1. Do both FieldAssigns need to have the transient modifier? Or just any one? Or the first one?
  2. What happens if the modifiers conflict (e.g. one transient FieldAssign transient, one final FieldAssign)?
2. What would be the canonical version of Java's "static final long serialVersionUID = -1234567890123456789L"? Would this FieldAssign stay in self.initialize() necessarily (which would be conceptually challenging if you think self.initialize() being executed at runtime, not at compile time, while static final values are indeed computed at compile time), or could this FieldAssign live outside? How can it live outside?

**Comment by baroquebobcat** [comment]
The other issue with having them live on assignments is that it's possible that in the future, when VarHandles or something like it are added to the JVM that we could actually make a single assignment or access volatile.

Currently we have an AST node for field declarations, but we don't have syntax for it. Maybe it'd make sense to put the modifiers there, and then we could decide on a syntax, starting with just a macro. Once the compiler supports all the modifiers we can either intrinsify the macro or we could replace it with a literal.

Since Mirah's classes aren't objects, there's a number of approaches we could look at for syntax that we couldn't do with Ruby, but I think we should take a little more time on it.

For serialVersionUID, I think it'd be cool if we added an extension on Serializable for setting it. Right now there's no callback for inheritance, but things like this make me wonder if it would make sense to have a macro callback for extensions that happens on inheriting from extended types.

**Comment by felixvf** [comment]
I've played a little with FieldDeclarations. It turns out that synthesizing a FieldDeclaration is possible, but merging multiple FieldDeclarations at the right time during compilation is a mess. That's why I create FieldAnnotationRequest as an interface between the macro and the compiler in https://github.com/mirah/mirah/pull/302/files.

Callbacks on inheritance would be cool. But I do not see how callbacks in java::io::Serializable would be able to set a unique serialVersionUID per class (except maybe by determining it from the name of the class). This would still leave open the question how to set the serialVersionUID to a different value than the auto-generated one.

**Pull request closed without merging**
