### PR TITLE
Set signatures in field members of ByteCodeMirrors

### PR DESCRIPTION
**Pull request by shannah**
Related to https://groups.google.com/d/msg/mirah/A6dcQ-cFSFk/jO6U73JUeeIJ

### CODE REVIEW

**Comment by baroquebobcat** [comment]
Thanks. Do you think you could write a regression test?

**Comment by shannah** [comment]
Yes.  I haven't contributed any regression tests to mirah before.  Can you give me a pointer as to where to put it, and what it should look like?

**Comment by shannah** [comment]
In my own tests, I've hit a problem with this one actually.  I need to make a few more changes to make it all work.

**Comment by baroquebobcat** [comment]
Here's where I think it should go: https://github.com/mirah/mirah/blob/master/test/mirrors/bytecode_mirror_test.rb

**Pull request merged**
