### PR TITLE
Fix some bugs with respect to constants.

### PR DESCRIPTION
**Pull request by felixvf**
Constants can now use local variables in the code which initializes them. This fixes https://github.com/mirah/mirah/issues/399.
Constants are now public (as intended). This fixes https://github.com/mirah/mirah/issues/400.
There is now a test which asserts that constants be not initialized in instance methods. This partially implements https://github.com/mirah/mirah/issues/401.

### CODE REVIEW

**Comment by uujava** [comment]
I'd change isFinal approach a bit. Do not introduce isFinal in ast, but calculate flags from FieldAssign -> FieldDefinition modifiers as we do for methods.  Pass this flag to typeSystem.createField instead of isStatic/isFinal. So we support additional flags for free for future (example - protected fields)

**Comment by uujava** [comment]
I've reimlemented this a bit in uujava/mirah:merge_fix_constants
- Do not support local variables in constant initialized blocks for now, but guess it could be implemented in class cleanup without parser change.

**Comment by felixvf** [comment]
@uujava I have tried to use your commits (https://github.com/uujava/mirah/commits/231a4f5390e7aaa46a4ba7cf66d901218eac0b44) to remove `isFinal` as well as `isStatic`. However, this does not seem to be straightforward, as your code depends on features which are available in your Mirah fork only, not in upstream Mirah.

It seems that your Mirah fork has deviated quite a bit from upstream Mirah. It would be nice if you could create pull requests for each of your features such that we can get your Mirah fork and upstream Mirah into sync again. Once your changes have landed, I'm happy to replace `isFinal` as well as `isStatic`. But until that happens, it does not seem to be worth the effort to replicate your fork's features just for the purpose of removing these 2 flags, without actually replicating your fork (by separate pull requests).

@baroquebobcat It would be nice if you could review this pull request, as it is already 8 months old and other pull requests yet to come build on it.

**Comment by uujava** [comment]
I'm definitely now far away from origin master in my release branch. Not sure I would have a time to merge all that work as a "per feature" pull request basis. 
There are also couple of things that prevents me from start to work on the merge - I prefer to go with a list of incompatible features: 
 - https://github.com/mirah/mirah/pull/435
 - modifiers keywords in the parser
 - java doc support in the parser

There are dozen of minor fixes and features implemented. I'm afraid that without much activity in mirah  it's easier for me to support my fork.

**Comment by felixvf** [comment]
I've updated the implementation.

@uujava I've removed the isFinal in the AST again. It should be now as you wish.
@baroquebobcat Any objections?

**Pull request merged**
