### PR TITLE
Fix bug https://github.com/mirah/mirah/issues/417.

### PR DESCRIPTION
**Pull request by felixvf**

### CODE REVIEW

**Comment by uujava** [comment]
check comments https://github.com/mirah/mirah/issues/417 when reviewing this pull request

**Comment by baroquebobcat** [comment]
:+1:  :ship: Ship it!

**Comment by baroquebobcat** [comment]
Looks like merging this caused the master branch's build to fail. I'll look at it in the morning.

**Comment by ribrdb** [comment]
Hmm, it builds for me. What failure are you seeing?

**Comment by felixvf** [comment]
> Hmm, it builds for me. What failure are you seeing?

This failure https://travis-ci.org/mirah/mirah/builds/112736283, I guess.

**Comment by baroquebobcat** [comment]
Could you add a pending to the one test that's failing? After that, I think this works.

**Comment by uujava** [comment]
fixed tests in #434

**Pull request merged**
